In [1]:
import numpy as np

def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def sigmoid_derivative(x):
    return x * (1 - x)

tr_inputs = np.array([[0,0,1],
                      [1,1,1],
                      [1,0,1],
                      [0,1,1]])

tr_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('synaptic_weights before training : \n', synaptic_weights)

for iteration in range(200000):
    
    input_layer = tr_inputs
    
    outputs = sigmoid(np.dot(tr_inputs, synaptic_weights))
    
    error = tr_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('synaptic_weights after training : \n', synaptic_weights)    

print('outputs after training: \n', outputs)

synaptic_weights before training : 
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
synaptic_weights after training : 
 [[12.70627854]
 [-0.20392447]
 [-6.14946022]]
outputs after training: 
 [[0.00213009]
 [0.99826132]
 [0.99858161]
 [0.00173782]]
